#!/bin/bash

cd /workspace

git config --global --add safe.directory /workspace

# install python dependencies:
pip install -r /workspace/requirements.txt

# install pre-commit hooks to git:
pre-commit install
